In [6]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [8]:
A=tf.constant([[4,3],[5,2]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 2]], dtype=int32)>

In [15]:
V=tf.Variable([[3,1],[5,2]])
V
B=tf.constant([[7,8],[3,5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [3, 5]], dtype=int32)>

In [18]:
AB_concatenated=tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [5, 2, 3, 5]], dtype=int32)>

In [20]:
AB_concatenated=tf.concat(values=[A,B],axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 2],
       [7, 8],
       [3, 5]], dtype=int32)>

In [24]:
tensor=tf.zeros(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [25]:
tensor=tf.ones(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [29]:
reshaped_tensor=tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [31]:
tesor=tf.random.uniform(shape=[3,4],dtype=tf.float32)
tesor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.9539702 , 0.6636356 , 0.6228719 , 0.59888697],
       [0.24387419, 0.02947521, 0.66687286, 0.9914626 ],
       [0.00426376, 0.38971114, 0.6925868 , 0.6890273 ]], dtype=float32)>

In [33]:
tensor_as_int=tf.cast(tensor,tf.int32)

In [35]:
a=tf.transpose(tesor)
a

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.9539702 , 0.24387419, 0.00426376],
       [0.6636356 , 0.02947521, 0.38971114],
       [0.6228719 , 0.66687286, 0.6925868 ],
       [0.59888697, 0.9914626 , 0.6890273 ]], dtype=float32)>

In [37]:
A=tf.constant([[5,8],[3,5]])

v=tf.constant([[4],[3]])

Av=tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [27]], dtype=int32)>